### ISSUE TITLE
installation way please 

### ISSUE THREAD

**Issue by houssamboudiar** [simon-fraser/MusicTube-Player#1]
downloaded it still cant install it

**Comment by greenhalos** [comment]
It worked fine for me: 
I downloaded this: https://github.com/simon-fraser/MusicTube-Player/releases/download/1.4.2/MusicTube.Player-darwin-x64.zip

Unpacked it

Double clicked on the MusicTube-Player.app

You maybe need to allow the app to run: Go to your System Preferences > Security & Privacy > General: On the bottom there should be a button to Open the MusicTube-Player App.

**Comment by houssamboudiar** [comment]
> It worked fine for me:
> I downloaded this: https://github.com/simon-fraser/MusicTube-Player/releases/download/1.4.2/MusicTube.Player-darwin-x64.zip
> 
> Unpacked it
> 
> Double clicked on the MusicTube-Player.app
> 
> You maybe need to allow the app to run: Go to your System Preferences > Security & Privacy > General: On the bottom there should be a button to Open the MusicTube-Player App.

oh thanks for the flash reply i will try it now

**Comment by simon-fraser** [comment]
Yes @greenhalos is quite right, the application is in the zip file, so after unpacking it, you can either double click to run or drag into your application folder and run from there.

Because It is not a signed (verified) application you might need to go into System Preferences > Security & Privacy and allow MusicTube-Player.
